### ISSUE TITLE
Is there a way to have a tick for each stack?

### ISSUE THREAD

**Issue by autra** [everestate/chartjs-plugin-waterfall#10]
I want to reproduce something like https://codepen.io/plotly/pen/qdLQJB (this one is with plotly.js).

Notice that each stack has a tick label (Product revenue, service revenue etc...). Is there a way to achieve such a thing with this plugin? 

I tried to emulate this by having dataset.data with several elements, but I had the impression that this plugin doesn't support that yet.

Thanks in advance for your response.

**Comment by MartinDawson** [comment]
This should definitely be possible. If I can it’s just putting labels on
your data I think. The exact same way as you do it with chartjs normally. I
can check later if I have time.

**Comment by autra** [comment]
Oh [I got this](http://trancart.eu/chart_test_4.html), thanks!

This last attempt doesn't have the lines though, possibly because the code [ignores all but the first element of data here](https://github.com/everestate/chartjs-plugin-waterfall/blob/master/src/drawStepLines.js#L84).

 (but I don't really want these, as I'd prefer dashed lines like so ![](https://upload.wikimedia.org/wikipedia/commons/3/3f/Waterfallchart_ex2.jpg)
)

If you're curious, here are my attempts:
- http://trancart.eu/chart_test.html my initial attempt, similar to your example (actually it's nearly the same as the example linked in the README). It works fine but I don't have the labels on the axis like the codepen I linked
- So then I tried to put a labels array in `dat` : http://trancart.eu/chart_test_2.html Here you can see that all the bars are grouped under the first label. Indeed, my data arrays have only one element, so I understand why chartjs would do this.
- I tried to fill the remaining slots in the data arrays with 0: http://trancart.eu/chart_test_3.html it's *nearly* that, but the width of each bars is scaled down to give space to 0 bars.
- Then I figured that actually, I should only have one dataset, and tried to put several values in the dummyStack too : http://trancart.eu/chart_test_4.html . and that worked!

**Comment by MartinDawson** [comment]
Nice, the lines from each one probably don’t support dashed lines natively.

You’d need to modify the source code.

**Comment by autra** [comment]
Yep!

Thanks for your help Martin.

**Comment by datainvestor** [comment]
@autra Hey I was wondering how did you add labels for x axis for each of the stacks? Im trying to do this but finding it pretty hard.

**Comment by autra** [comment]
@datainvestor just check the official examples (for instance https://codepen.io/plotly/pen/qdLQJB)

**Comment by datainvestor** [comment]
@autra But this is plotly not chartjs. So it is not possible to do this in chartjs?

**Comment by MartinDawson** [comment]
I have no idea about plotly but this plugin is created for chartjs and not
tested with 3rd party libraries

**Comment by datainvestor** [comment]
Yes I dont care about plotly, I'm just trying to somehow enable labels in waterfall chart using chart.js
but adding this to options:
```
      scales: {
        xAxes: [
          {
            display: true,
             ticks: {
                    display: true 
                }
          }
        ]
      }
```
Does not work. Any ideas how should it be added?

**Comment by autra** [comment]
Oh sorry wrong link. I think I deleted my examples, and 1 year ago is too long for my memory. I completely forgot, but it seems the first comment of Martin had helped me somehow ;-)

**Comment by anubhavng** [comment]
Hi @autra Can you please provide an working example for ticks?
