### ISSUE TITLE
TypeError in drawStepLines

### ISSUE THREAD

**Issue by nilssiegle** [everestate/chartjs-plugin-waterfall#7]
I just installed the plugin with ChartsJS 2.7.2, and set up an example according to the [GitHubGist by EdwinChua](https://gist.github.com/EdwinChua/0a5d66dc561fe7d3866021b18a320585).
The transparent dummies get printed correctly, but I don't see any step lines, and the tooltips are very laggy and partly malformed (see picture).

![waterfall_plugin_error](https://user-images.githubusercontent.com/33981934/44161313-41eb4180-a0bd-11e8-8a30-c7ee44041f0a.PNG)

The console reports the following error:

```
TypeError: e is not a function in drawStepLines.js:78:26
```

This error gets thrown every time I move my mouse over an element of the chart, including the dummy elements.

I have no other plugins installed, and no specific options set for the chart.

**Comment by MartinDawson** [comment]
Ok, I'll try and test the gist tomorrow or this week. I admit I didn't test it when it was added.

**Comment by MartinDawson** [comment]
What browser are on running it on?

**Comment by nilssiegle** [comment]
I tested it on FireFox (61.0.2), FireFox Developer Edition (62.0b17) and Edge (42.17134.1.0).  
Edge gives me a slightly different error, `SCRIPT5007: Object expected` on line 77 of `drawStepLines.js`.

For the record: I am not using node, I just integrated the folder into my project and pointed to `chartjs-plugin-waterfall/dist/chartjs-plugin-waterfall.min.js`, just as in the gist. But that should not be the problem.

**Comment by nilssiegle** [comment]
I picked up testing again, and it seems to be an issue with lodash.  
After setting all `DEBUG`-variables to `true` and switching to the regular script instead of the minified, the error now sais `TypeError: groupBy is not a function`. So basically the same, just with a name.  
But it remains the only error, and if something went wrong while importing the function from lodash, I would have gotten an error there, or am I wrong?

I'm quite new to JS, so my understanding of modules etc. might be wrong. It would be really helpful if you could check the gist, maybe I am just missing something obvious here.

**Comment by MartinDawson** [comment]
Can you add these instead of the `lodash` cdn at the top of the file:

`https://cdn.jsdelivr.net/npm/lodash.groupby@4.6.0/index.min.js`
`https://cdn.jsdelivr.net/npm/lodash.merge@4.6.1/index.min.js`

We import these lodash files specifically instead of the entire 'lodash' package to reduce the file size. The CDN for lodash in the gist is incorrect and it should link to the ones above.

Thanks.

**Comment by birkansava** [comment]
> Can you add these instead of the `lodash` cdn at the top of the file:
> 
> ```js
> https://cdn.jsdelivr.net/npm/lodash.groupby@4.6.0/index.min.js
> https://cdn.jsdelivr.net/npm/lodash.merge@4.6.1/index.min.js
> ```
> 
> We import these lodash files specifically instead of the entire 'lodash' package to reduce the file size. The CDN for lodash in the gist is incorrect and it should link to the ones above.
> 
> Thanks.

It throws error like : module is not defined
